#!/usr/bin/env sh

pnpm run check-translations
if [ $? -ne 0 ]; then
  echo "pre-commit: translation check failed" >&2
  exit 1
fi

pnpm run lint
if [ $? -ne 0 ]; then
  echo "pre-commit: linting failed" >&2
  exit 1
fi

exit 0
